[build]
builder = "NIXPACKS"
buildCommand = "npx pnpm@9 install && npx pnpm@9 --filter client build && npx pnpm@9 --filter server build"

[deploy]
startCommand = "NODE_ENV=production node packages/server/dist/app.js"
